export const MovementErrorCode = {
  MOVEMENT_NOT_FOUND: 'MOVEMENT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  INVALID_PERIOD: 'INVALID_PERIOD',
} as const;
